name: Auto Update Coverage KML

on:
  workflow_dispatch: # Agar tombol 'Run workflow' muncul

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate KML
        run: |
          curl -s "https://sapiderman.myrepublic.net.id/api/v1/air/coverage-data" > raw_data.json
          python3 - <<EOF
          import json
          try:
              with open('raw_data.json') as f:
                  data = json.load(f)
              if data[0] != data[-1]: data.append(data[0])
              header = """<?xml version="1.0" encoding="UTF-8"?>
          <kml xmlns="http://www.opengis.net/kml/2.2">
          <Document>
            <Style id="mrAir"><PolyStyle><color>4D6C2D91</color></PolyStyle></Style>
            <Placemark><styleUrl>#mrAir</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>"""
              coords = " ".join([f"{p[0]},{p[1]},0" for p in data])
              footer = """</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Document></kml>"""
              with open('coverage_live.kml', 'w') as out:
                  out.write(header + coords + footer)
          except Exception as e: print(e)
          EOF
      - name: Push KML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add coverage_live.kml
          git commit -m "Update KML" || exit 0
          git push
